### ISSUE TITLE
fatal: curl failed with code 3

### ISSUE THREAD

**Issue by imwireless** [ChaoticWeg/discord.sh#27] opened 2021-03-04 05:35 UTC
Just tested your discord script and am getting an error code on curl. 

This happens when using your example simple text.  

Any suggestions?
Using your latest release.

**Comment by fieu** [comment] 2021-03-04 09:34
Hello @imwireless, can you please give us the steps do reproduce the error? Saying you have an error is not as helpful as the full context of your use.

**Comment by imwireless** [comment] 2021-03-04 14:06
I put .webhook with my discord webhook in my Media folder.  I then added the discord.sh file as is with no edits.  I then ran the sample text you have in your README.MD and it returned a curl (3) error.  

`./discord.sh --webhook-url="$WEBHOOK" --text "Hello, world!"`

**Comment by fieu** [comment] 2021-03-06 16:52
It seems that the problem is not with `discord.sh` but with `curl`.

Error code 3 from `curl` means `CURLE_URL_MALFORMAT` which is to say the URL was not properly formatted.

Check [here](https://curl.se/libcurl/c/libcurl-errors.html) for more information.

**Comment by imwireless** [comment] 2021-03-07 00:15
> It seems that the problem is not with `discord.sh` but with `curl`.
> 
> Error code 3 from `curl` means `CURLE_URL_MALFORMAT` which is to say the URL was not properly formatted.
> 
> Check [here](https://curl.se/libcurl/c/libcurl-errors.html) for more information.

Any suggestions?  I mean in my example it's a simple url.

**Comment by fieu** [comment] 2021-03-09 17:34
What are the contents of `$WEBHOOK_URL` ?

**Comment by davidjmorin** [comment] 2021-03-28 16:35
> What are the contents of `$WEBHOOK_URL` ?

Only thing in that file is the discord webhook URL.  No spaces or anything.  I also tried chmod 777 and setting it as executable.  Not sure whats im missing here.

**Comment by fieu** [comment] 2021-03-28 19:16
Hmm, I am not sure. Can you hand me all the files in question within your testing context? Feel free to redact part of the webhook URL.

**Comment by fieu** [comment] 2021-04-04 04:32
Closing this issue as it seems to have been abandoned.

**Closed by fieu** 2021-04-04 04:32 UTC
Labels: need info
